force-app/main/default/objects/DebugLog__c/DebugLog__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugLogEvent__e/DebugLogEvent__e.object-meta.xml
<CustomObject>
    <label>Debug Log Event</label>
    <pluralLabel>Debug Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/DebugLogEvent__e/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugLogEvent__e/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugLogEvent__e/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugLog.cls
public class DebugLog {
    private String fileName;
    private String methodName;
    private String details;

    public DebugLog(String fileName, String methodName, String details){
        this.fileName = fileName;
        this.methodName = methodName;
        this.details = details;
    }

    public DebugLog(String fileName, String methodName, Exception error){
        this.fileName = fileName;
        this.methodName = methodName;
        this.details = error.getStackTraceString() + '\n' + error.getMessage();
    }

    public void saveLog(){
        DebugLog__c newLog = new DebugLog__c();
        newLog.fileName__c = fileName;
        newLog.methodName__c = methodName;
        newLog.details__c = details;
        insert newLog;
    }

    public void publishLog(){
        DebugLogEvent__e logEvent = new DebugLogEvent__e();
        logEvent.fileName__c = fileName;
        logEvent.methodName__c = methodName;
        logEvent.details__c = details;
        EventBus.publish(logEvent);
    }
}